version: '3.1'

services:
  mysql:
    image: mysql:8.0
    container_name: app-mysql
    restart: always
    ports:
      - '33006:3306'
    environment:
      MYSQL_DATABASE: testDB
      MYSQL_ROOT_PASSWORD: password
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci